name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - uses: chromaui/action@v1
        with:
          projectToken: c3a865a5d02d
          token: ${{ secrets.GITHUB_TOKEN }}
